### ISSUE TITLE
OID: organizationUnitName

### ISSUE THREAD

**Issue by FGasper** [gknocke/Crypt-PKCS10#16]
http://oid-info.com/get/2.5.4.11

I am not sure if the above is authoritative, but it appears to be the case that OpenSSL has this one wrong: the canonical text for this OID is “organizationUnitName”, not “organizationalUnitName”.

Of course, this may not be fixable if things depend on the status quo. Still, I thought it worth pointing out.

**Comment by tlhackque** [comment]
Looks as though your reference is wrong, you might want to submit a bug report.

[ITU520](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-X.520-201210-S!!PDF-E&type=items) has the PDF of that standard. Search for "unitname", and we find that OpenSSL is consistent with it.  The ITU standard is pay-to-view:

From ITU 520:
6.4.2 Organizational Unit Name
The Organizational Unit Name attribute type specifies an organizational unit. When used as a component of a directory name, it identifies an organizational unit with which the named object is affiliated.
The designated organizational unit is understood to be part of an organization designated by an organizationName attribute. It follows that if an Organizational Unit Name attribute is used in a directory name, it shall be associated with an organizationName attribute.
ISO/IEC 9594-6:2014 (E)
Rec. ITU-T X.520 (10/2012) 11
An attribute value for Organizational Unit Name is a string chosen by the organization of which it is part (e.g., OU ="Technology Division"). Note that the commonly used abbreviation "TD" would be a separate and alternative attribute value.
Example
O = "Scottel", OU = "TD"
````
organizationalUnitName ATTRIBUTE ::= {
SUBTYPE OF name
WITH SYNTAX UnboundedDirectoryString
LDAP-SYNTAX directoryString.&id
LDAP-NAME {"ou"}
ID id-at-organizationalUnitName }
````

**Comment by tlhackque** [comment]
Correction: the ISO standard is pay-to-view.  (I fixed the previous comment, which previously said the ITU standard.)

**Comment by FGasper** [comment]
It really is confusing trying to follow all of the standards for OIDs … especially when they’re paywalled.

**Comment by tlhackque** [comment]
Sure is.  And when "open" standards refer to the paywalled ones, it's really annoying.

Luckily, in this case everyone except for the OID reference site agrees :-)

I'm closing this issue since everyone seems to be in sync.  Thanks for raising your concern.
