### ISSUE TITLE
Development release(s) of 1.4

### ISSUE THREAD

**Issue by tlhackque** [gknocke/Crypt-PKCS10#7]
I've released a development version of 1.4 (V1.4_01) to CPAN.  If you don't find it there, it's already on MetaCPAN at https://metacpan.org/release/TLHACKQUE/Crypt-PKCS10-1.401-TRIAL.  And the github repository is now tagged.

There are API changes (improvements), though there is a compatibility mode.

The documentation is somewhat better, but still needs work.

Feedback and testing is welcome.  (As are more regression tests!)

Releases are tagged in GIT.

This issue will remain open for general feedback on V1.04 until general release.

Feel free to open separate issues for significant bugs.

**Comment by tlhackque** [comment]
V1.4_02 released.  

- Fixed a minor API regression with API v0
- now decode certificatePolicies correctly -- and M$ ApplicationCertificatePolicies completely (API v1)
- new api for turning OID names returned from Crypt::PKCS10 into OIDs (API v1 only)
- some internal cleanup/optimizations.

Enjoy.

**Comment by gknocke** [comment]
Great work! I do have a comment, though.

Currently, the CSR is parsed in its entirety. In case a part of the CSR cannot be parsed, croak is called. But can we always assume to be able to parse the entire CSR? I've just tested the module against a CSR that would require the ASN.1 definition of ENROLLMENT_CSP_PROVIDER. As this ASN.1 definition does not exists, croak() ist called. As a result, even the accessible information in the CSR (public key etc.) cannot be parsed anymore.

From my understanding we cannot cover every case of certificate extensions. Neither OpenSSL can. However, OpenSSL can still work with that CSR as other information can still regularly be parsed.

I suggest to not parse the CSR in its entirety but only the parts where we don't expect failures. The other parts should be parsed separately so if they fail, we can still work on that CSR.

**Comment by tlhackque** [comment]
Agree that needs to be handled better.  Send me the CSR & I'll see where things are going wrong.  

There's an 'optional' flag that gets passed to the macro lookup; there's probably a case where I missed setting it.  We weren't croak()ing in cases where the ASN.1 was expected; now we do.  We shouldn't in the cases where we aren't sure...

I could also use a test case for the Microsoft Certificate Template; you have a special handler that I haven't looked at yet, though I just found the ASN.1 for it...

**Comment by gknocke** [comment]
This comment is based on you current version in your branch:

1) Your update fixed the previously mentioned issue!
2) Exception handling missing in 
https://github.com/tlhackque/Crypt-PKCS10/blob/master/lib/Crypt/PKCS10.pm#L955
In case "subject" is not part of the CSR, the program will try to access the uninitialized value in the hash.
3) extensionValue('extKeyUsage') returns an array if multiple values are given but extensionValue('keyUsage') returns a string that lists the attributes comma separated. This behavior might be justified but my first intention would be to either receive a string in both cases or an array in both cases.

**Comment by tlhackque** [comment]
1) Good, thanks for verifying.

2) I looked at that.  The subject isn't optional, see https://tools.ietf.org/html/rfc2986#page-5.  The subjectDN can be empty (in some cases replaced by subjectAltName).  I think I introduced a bug if it's null (has no components). Should be fixed in commit 554d88b81313e9aa1684332fb4e76054b98bc09b -- please try your test case.  (It's really helpful if you can provide a reproducer; it's hard for me to generate arbitrary CSRs.)

3) I agree that's inconsistent.  But that's the way the code has always worked.  I have tried not to make unnecessary changes to the API, even where it's not pretty.

The difference seems to be because one is a bitstring, and the other an array of OIDs.  I can make keyUsage do the same thing as extKeyUsage (can get either a string or an array of strings depending on $format).  It's still inconsistent in that there are no OIDs for the bits.  (By the way, the same is true for the Netscape cert type bitstring.)

It's another API change.  At some point there will have to be regression tests for all the API options.  This change is on my queue... Tests are another project.

Thanks for the feedback.  Let me know when you find the next bug...

**Comment by tlhackque** [comment]
Bitstrings now return array; string is available with extensionValue('keyUsage',1).

Commit d6802a8748d95299291cea51ec9dc7a6f8383aec

**Comment by tlhackque** [comment]
Version 1.4_03 (development) released to CPAN and git.

Notable changes:
 - new() will never generate an exception: returns undef - call Crypt::PKCS10->error for reason.
 - new() will accept a file handle.
 - better heuristics for decoding
 - numeric OIDs can be used when calling extensionValue, attributes(), and extensionPresent
 - tests have been expanded - and may be useful as examples
 - Crypt::PKCS10 object can be stringified, e.g. print "$decoded"
 - bug fixes and error handling improvements
 - the documentation has been updated, but still needs work.

See the README and Commitlog for details and a more complete list.

Note that while the deprecated V0 API is stable, the V1 API is not yet frozen.  I think the changes are improvements, but applications may have to make changes.

The API will, of course, be frozen at the final V1.4 release.

Feedback welcome.

**Comment by tlhackque** [comment]
V1.4_04 (development) released.

Fixes test failures on recent Perl, some packaging nits.

**Comment by tlhackque** [comment]
V1.6 has been released.  Closing this issue.
