### ISSUE TITLE
Make algorithm parameters available via API

### ISSUE THREAD

**Issue by mbartosch** [gknocke/Crypt-PKCS10#9]
When using ECDSA requests it may be interesting for the caller to find out the EC curve name/OID used for the public key.

This requires access to the "parameters" section in AlgorithmIdentifier which is currently discarded (see Algorithms ::= ... ANY).

I tried to modify the ASN.1 definition to the following:
    AlgorithmIdentifier ::= SEQUENCE {
      algorithm  OBJECT IDENTIFIER,
      parameters ANY OPTIONAL}

Then parameters becomes accessible in the %decoded hash as an unparsed bit string. Changing ANY to ObjectIdentifier in the definition causes the parser to choke, though.
I currently don't have time to investigate further and will have a look later.

**Comment by tlhackque** [comment]
I also don't have time to dig far into this, but here are a few hints:

IIRC you have to create a custom parser & ASN.1 to deal with the optional segment; the code has to check for presence, then call the parser (_init)  with the appropriate node name & finally decode the bitstring with the parser.  

I haven't looked at this in a while, but I believe there are examples in the existing code.  Cert policies is fairly complex...  There is code for public key info, and the %special hash will also be of interest.

It would be good to end up with a consistent mechanism for RSA keys - e.g. fetching parameters for RSA should return the key length; fetching for ECDSA should return the OID, but might also return the corresponding key length...

If you get stuck, feel free to contact me off-line & I'll try to provide further help.  (cpan.org)

**Comment by tlhackque** [comment]
There is a highly experimental version of this in my repo.  (https://github.com/tlhackque/Crypt-PKCS10)

Feedback is welcome.

**Comment by tlhackque** [comment]
Fixed in V1.7

Standard parameters - key type, length and public key components - are available via subjectPublicKeyParams.

Gory detail (e.g. the curve definition) is available via subjectPublicKeyParams(1) for ECC keys.
